### ISSUE TITLE
Docker containers do not run correctly on Mac M1

### ISSUE THREAD

**Issue by davidpalmeruk** [logicmonitor/hipster#7]
Following getting docker-compose to work via workaround the containers presents three faults.

Cartservice:
Attaching to hipster-main-ad-1, hipster-main-cart-1, hipster-main-checkout-1, hipster-main-currency-1, hipster-main-email-1, hipster-main-frontend-1, hipster-main-lmotel-1, hipster-main-payment-1, hipster-main-productcatlog-1, hipster-main-recommended-1, hipster-main-shipping-1
hipster-main-cart-1           | Failed to resolve full path of the current executable [/proc/self/exe]
hipster-main-cart-1 exited with code 133

Emailservice:
2023-01-31 11:28:54 E0131 11:28:54.418165543      26 ssl_transport_security.cc:1446] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

Adservice:
2023-01-31 11:50:31 Caused by: io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: OTLP endpoint must be a valid URL: "http://host.docker.internal:4318/v1/traces"
2023-01-31 11:50:31 Caused by: java.net.MalformedURLException: no protocol: "http://host.docker.internal:4318/v1/traces"

Checking the "/proc/self/exe" fault suggest a docker platform level issue hitting Mac silicon so compatibility needs to be confirmed.

As a workaround attempted forcing docker to use the linux/amd64 platform flag on cartservice which can build yet doesn't resolve the issue.

docker-compose.yml file
>  cart:
>    build: ./cartservice
>    platform: linux/amd64
>    ports:
>      - 80:80
>    extra_hosts:
>      - "host.docker.internal:host-gateway"

**Comment by davidpalmeruk** [comment]
Found comments that officially the Hipster shop does not support Apple/ARM based images/builds. Using BuildX to create x64 containers, or by updating dockerfiles to workaround the hard coded x64 images are discussed here: https://github.com/GoogleCloudPlatform/microservices-demo/issues/622

**Comment by NimJay** [comment]
Thanks for reporting your issue, @LM-davepalmer.

Did the workaround that you mentioned (and also mentioned in https://github.com/GoogleCloudPlatform/microservices-demo/issues/622) end up working for you?

~If so, I think we should close this issue as it's a duplicate of https://github.com/GoogleCloudPlatform/microservices-demo/issues/622, which we hope to address in 2023.~ I just realized this is a different repository. Sorry!

**Comment by davidpalmeruk** [comment]
No success when attempting any workarounds.
Running using BuildX instead of default docker build:

..export values per github guide...
docker buildx bake --set '*.platform=linux/amd64' --no-cache -f docker-compose.yml

**Test 1:** Updated dockerfile for cartservice, checkoutservice, productcataglogservice and shippingservice to all use the latest health _probe version which supports multi-platform. Successful going forward.

> RUN GRPC_HEALTH_PROBE_VERSION=v0.4.15 && \
>    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health->probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \

**Test 2:** Update cartservice.csproj to include runtime identifier - no change, builds yet cartservice exits (139).
`<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
  </PropertyGroup>`

Same error as original issue. Container stops at build, exit 133.
2023-02-01 11:30:23 Failed to resolve full path of the current executable [/proc/self/exe]

**Test 3:** Update dockerfile: "FROM mcr.microsoft.com/dotnet/sdk:7.0 as builder"
And cartservice.csproj:
`<TargetFramework>net7.0</TargetFramework>`

>2023-02-01 11:19:45 Failed to load /app/libcoreclr.so, error: Error relocating /app/libcoreclr.so: memfd_create: symbol >not found
>2023-02-01 11:19:45 qemu: uncaught target signal 11 (Segmentation fault) - core dumped

New error in container log, site not fully functional, yet build completes via NET 7.0 and container remains running.

Compatibility with Mac using Apple silicon (arm64) remains an issue and there is no ETA for Google to officially support arm64 or multi-arch images for the store.
Noted, our lmotel:image is also AMD64 compatible only yet can function via emulation layer.
Failure seems purely due to docker's emulation layer unable to start the cartservice correctly.

**Comment by davidpalmeruk** [comment]
Good news!
So on the latest Docker Desktop for Mac (v4.17.0) the emulation issue can be resolved. Issue remains on default settings (for docker-compose or docker buildx. It remains possible that native M1/M2, Arm64 support would be valuable for LMotel agent and collectors.

Yet using the stock cloned files, plus existing install instructions an M1 Mac can run the store successfully if setting a beta feature to true - it is disabled by default:
"Use Rosetta for x86/amd64 emulation of Apple Silicon"

<img width="1230" alt="Screenshot 2023-03-05 at 14 56 57" src="https://user-images.githubusercontent.com/124046114/222969211-f8e685d7-953b-4dda-8432-e63f31987390.png">
